### ISSUE TITLE
Missing license.

### ISSUE THREAD

**Issue by cldershem** [fzyzcjy/flutter_rust_bridge#1]
**Describe the bug**
This code is not have a license and is therefore closed source.

**Expected behavior**
A LICENSE file in the repository.

**Additional context**
Posting the repository publicly [does not](https://choosealicense.com/no-permission/) make it open source.

Anything you write is automatically copyrighted unless you explicitly license it. The vast majority of Rust projects use the MIT license, but you can do whatever you feel is best. I think the website I linked above can walk you through choosing a license and adding a LICENSE file to your codebase.

**Comment by derekdreery** [comment]
Thanks again for making this code public, it's awesome and will help so many people.

But yes it won't be possible for people to use it in production/at work unless it has a license that allows them to. The parts of the library that are used in users final binaries would need to be permissive (e.g. MIT), but the codegen parts could be more copyleft if that is your preference, since they do not appear in the binary downstream.

**Comment by fzyzcjy** [comment]
Nice catch! I will add one definitely.

**Comment by fzyzcjy** [comment]
Done. Thanks for the suggestions!
