### ISSUE TITLE
Is there any way to make a plug-in package that is not uploaded to the pub and referenced by multiple local flutter projects？

### ISSUE THREAD

**Issue by cyz1901** [fzyzcjy/flutter_rust_bridge#1029]
The tutorial seems to need to upload something to github or gitlab, but I use bitbucket....
https://cjycode.com/flutter_rust_bridge/library.html

**Comment by cyz1901** [comment]
And whether the tutorial needs to be updated
I faced some confusing places
<img width="719" alt="截屏2023-02-06 14 31 46" src="https://user-images.githubusercontent.com/36350890/216899616-4ec9cb79-5df1-441e-b50f-e3833ef5ec8d.png">
<img width="888" alt="截屏2023-02-06 14 32 02" src="https://user-images.githubusercontent.com/36350890/216899651-8ac9b0b3-6a27-4cf1-bb53-e430700d066b.png">

**Comment by cyz1901** [comment]
How should Cargo.toml content be generated？

and we will `flutter pub add library_name` after our plugin library upload to pub or github?

**Comment by cyz1901** [comment]
And i flow guide add flutter_rust_bridge to project
https://cjycode.com/flutter_rust_bridge/integrate.html

found
```
Error (Xcode): Undefined symbol: _drop_dart_object

Error (Xcode): Undefined symbol: _free_WireSyncReturn

Error (Xcode): Undefined symbol: _get_dart_object

Error (Xcode): Undefined symbol: _new_dart_opaque

Error (Xcode): Undefined symbol: _store_dart_post_cobject

Error (Xcode): Undefined symbol: _wire_greet
```


cargo.toml
```
[package]
name = "rust-native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flutter_rust_bridge = "1"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

```

**Comment by fzyzcjy** [comment]
IMHO it should not be hard to migrate from github/gitlab to bitbucket

also cc @GregoryConrad who implemented the helpful doc in https://github.com/fzyzcjy/flutter_rust_bridge/pull/899

**Comment by GregoryConrad** [comment]
Hi @cyz1901 !

Bitbucket is not a problem, although the CI workflows given in the docs will not work (because they are for GitHub actions) and you would have to adapt them to Bitbucket's equivalent. Also, you will need to set up the platform-specific build processes (i.e., the 3 CMakes and 2 `podspec`s) to point to the native libraries released on Bitbucket and not GitHub (unless you are only building the library locally and never publishing, in which case you wouldn't have to worry about that).

There are two `Cargo.toml`s. One is at your repository root and defines the Rust workspace to help IDEs and define the build output location. The second `Cargo.toml` is in `/packages/library_name/native` to define your project's output types, dependencies, etc. It looks like you made your own Cargo.toml, which is incorrect. Both `Cargo.toml`s are generated for you in the script here: https://cjycode.com/flutter_rust_bridge/library/dart_only.html

The `export` dart line is to export your Dart-only base library in your flutter wrapper. This is typically not a best practice in general, but is required for creating a library here because the flutter wrapper bundles the platform-specific binaries which require an exact version of the Dart-only base. The Dart-only package cannot export the assets (which it would be nice to have) until the Native Assets feature is released sometime in the future with Dart 3.

> and we will `flutter pub add library_name` after our plugin library upload to pub or github?

That command will only work if you publish `library_name` to pub. Otherwise, it will error out. Also, you would need to add `flutter_library_name` for flutter, and `library_name` for dart-only.

Your missing Xcode symbols are one (or both) of two things:

1. You did not follow https://cjycode.com/flutter_rust_bridge/library/platform_setup/ios_and_macos.html correctly, and perhaps missed the Swift file
2. You did not populate `/ios/Frameworks/` or `/macos/Frameworks/` with the XCFramework built from `build-apple.sh` with the correct name (something like `library_name-v0.0.0.xcframework.zip`)

Try to take some time to really read through the guide and understand it. Based on the errors you are having (with Xcode and the Cargo.tomls) it looks like you missed pieces here and there. Creating a native library (especially Rust) with the state of Dart as it is now is very tricky to do correctly and the guide tries to help you as much as possible, but it takes some time to digest all the material. I really wish it was easier, and it will be once native assets are released, but in the meantime it is a bit painful.

If you really want to get into it right away with an example, take a look at [mimir](https://github.com/GregoryConrad/mimir). Mimir is my library that I based that section of the docs around.
