### ISSUE TITLE
Do not add package:uuid/uuid.dart import in Dart unless it is actually used

### ISSUE THREAD

**Issue by GregoryConrad** [fzyzcjy/flutter_rust_bridge#1147]
Not sure in which exact version the `import 'package:uuid/uuid.dart';` was added on the Dart side, but it was within the last few weeks.

When creating a package with FRB, if you don't use any features in FRB requiring uuid, you shouldn't need to add it as a dependency. Then users of your package will then have a transitive dep on uuid and it could create version conflicts.

Workaround for now is adding `uuid: any` in pubspec, but ideally it shouldn't be needed at all.

**Comment by fzyzcjy** [comment]
Totally agree. At the same time, a few other dependencies may be removed as well. https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_dart/pubspec.yaml

The problem is, the frb_dart package does have a few helper functions for them. One way is that we inline those code into the generated dart code instead of putting them in runtime library. For uuid this may be possible since it is small enough (but for others maybe no).

**Comment by GregoryConrad** [comment]
bump

**Comment by GregoryConrad** [comment]
Bump

**Comment by gutenfries** [comment]
bump

**Comment by gutenfries** [comment]
Am I misunderstanding the objective, or has this already been implemented (without inlining)

| |
| --- |
| https://github.com/fzyzcjy/flutter_rust_bridge/blob/f74982796e7dd317d43f80153b0250fa8ea9aa20/frb_codegen/src/generator/dart/mod.rs#L229-L246 |

As another point, how would one go about inlining generated code from an external package?

**Comment by fzyzcjy** [comment]
@gutenfries IIRC the issue is not resolved yet, because uuid is still in `pubspec.yaml`, thus every package using frb will have dependency on uuid (though not used)
