### ISSUE TITLE
Action 'Post-Release' keeps failing

### ISSUE THREAD

**Issue by SoLongAndThanksForAllThePizza** [fzyzcjy/flutter_rust_bridge#1168]
I've noticed that the Action 'Post-Release' keeps failing even after I fixed the 'Install cargo ndk' phase. Specifically, the main problem is that it fails constantly in the 'Run Flutter Intergration Test' phase.
I noticed that there's a related issue (#47), but currently 'Run Flutter Intergration Test' keeps failing no matter how many times the Action is retried.
I've tried to look into the error log but it looks kind of confusing.

**Comment by fzyzcjy** [comment]
Yes it is failing currently, and I do not have much time to fix it :/ Feel free to PR and fix it!

**Comment by fzyzcjy** [comment]
Take your time and looking forward to it!

**Comment by fzyzcjy** [comment]
Looks interesting! IMHO in order to fix it, it may be even easier to *migrate* it. The history was:

1. initial version of CI and post-release
2. CI is refactored, now it mainly invokes the `justfile`, instead of hardcoded commands in the YAML files

Thus, one way is to migrate post-release to use the `justfile` as well. Then we even have better code reuse!

**Comment by fzyzcjy** [comment]
Definitely!

**Comment by fzyzcjy** [comment]
Good catch!

**Comment by fzyzcjy** [comment]
cc @huang12zheng who made the change :) IMHO making it named "pure_dart" looks a bit more consistent (since we have with_flutter and pure_dart_multi examples which seems to be named like this)

**Comment by fzyzcjy** [comment]
I think so. The CI (and post-release etc) are the main gatekeeper to ensure that we do not break anything (e.g. api compatibility, features, bugs, etc). If this change breaks something but CI does not complain, then we should improve our CI system!
