### ISSUE TITLE
Flutter / Dart test conventions

### ISSUE THREAD

**Issue by dcharkes** [fzyzcjy/flutter_rust_bridge#1261]
I see we have a lot of manually scripted integration tests running Dart and Flutter. 🚀 

Most of these tests reside in https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example. These tests are example projects and are run end to end as integration tests.

A couple of points of feedback from a Dart / Flutter package structure point of view:

1. The example cannot be tested with `dart test` or `flutter test`. The tests are not inside `test/` and are not named `*_test.dart`. Rather they are called `main.dart`.
2. The main package from a Dart point of view (folder `frb_dart`) has no `test/` folder either. In package:ffigen and package:jnigen we have tests in the `test/` folder that copy example projects to a temp folder and run all the required steps as a full end-to-end test. Moreover, we check in those tests that all the setup steps (building/installing the Rust code in this case, installing libclang in FFIgen's case, building packag:jni's dylib in JNIgen's case) have been done and either do them or output an error message on how to do them.

Currently, in order to assess test coverage, or to run the tests locally, we have to reverse engineer the commands from from `.github/ci.yaml`. Following the Dart / Flutter package conventions would clean this up.

P.S. I love this project. Keep up the good work! 😎

**Comment by dcharkes** [comment]
Context: https://docs.flutter.dev/packages-and-plugins/favorites#metrics

**Comment by fzyzcjy** [comment]
I see and will fix it soon. Thank you for the suggestion and the love of project!

**Comment by fzyzcjy** [comment]
I checked the problem a little bit and would like to hear more details:

1. For the pure_dart and pure_dart_multi example, I can add something like `test/main_test.dart`. However, these are not executed directly, but instead used Valgrind. Therefore, as you can see in `pure_dart/run.sh` (I know the whole thing is a bit messy...), I have to compile to AOT Dart. Then, one naive thought is just to add a wrapper: `test/main_test.dart` has nothing but `await executeTheProcess('valgrind ./run.sh')`; another way is to throw away Valgrind and directly execute the test.
2. For the with_flutter example, the test is executed by `flutter run integration_test/main.dart` in various Flutter platforms, i.e. it is already a standard Flutter test.
3. If I understand correctly, the code to be added into `frb_dart/test/...` will be nothing but a very thin wrapper, like `await executeTheProcess('flutter run integration_test/main.dart')` and `await executeTheProcess('valgrind frb_example/pure_dart/run.sh')`. Since I am not sure whether this is what you mean in the post, I would like to post it here before implementing it.

**Comment by fzyzcjy** [comment]
Thank you for the detailed reply! I am quite busy recently and will try to re-read carefully and reply within a day. :)

**Comment by fzyzcjy** [comment]
> Actually maybe we should consider using valgrind in FFIgen and JNIgen as well!

Btw Valgrind does not work well with Dart (at least in frb's context) :/ It yields a ton of invalid access errors (you can open any CI output to see this), and thus I am only using it to check memory leaks instead of memory accesses.

> A third type of test that we have in FFIgen and JNIgen is regenerating the generated code to see if it's correct. However, in flutter_rust_bridge the code generation is done in rust code not in Dart code. So it's better to have that covered in Rust tests instead of in Dart tests.

I think so. There are code generation tests in CI currently.

> And then a frb_dart/test/pure_dart/valgrind_test.dart that invokes the other tests with Process.run and valgrind. (Or you could even put that in frb_dart/test/pure_dart_valgrind/frb_test.dart which would give you dart test test/pure_dart as a way to run the tests without valgrind.)

Given that Valgrind works quite weakly in this repo (only check memory leak as mentioned above), for simplicity, I may want to omit the valgrind-test-in-`frb_dart/test` thing ;) Anyway, CI will catch everything even if a simple `dart test` passes.

> What do you think? Does it make sense to move the unit test code to frb_dart/test/ instead of having a wrapper script there?

I personally like the `frb_example/pure_dart`, because as this library promises, it is pure-Dart compatible. So users may expect to see two examples: One pure-dart example, one with-flutter example.

---

So I guess the main actionable goal is: Add something in `frb_dart/test` (say, `frb_dart/test/pure_dart/main_test.dart`), that effectively executes all those dart-to-rust calls currently in `frb_example/pure_dart/main.dart`.

There may be several ways given the conversations:

* Method 1 (simplest): If we do not care about self-contained tests in pub.dev. In `frb_dart/test/pure_dart/main_test.dart`, simply call the main() of `frb_example/pure_dart/main.dart`, without any Valgrind, so it can be run easily, with test coverage, etc.
* Method 2: If we care about self-contain. Maybe use symlinks to link frb_example/pure_dart into somewhere like frb_dart/symlink_frb_example_pure_dart, and let `frb_dart/test/pure_dart/main_test.dart` call it? However, it may be a bit more complicated, since some code rely on the relative paths, and a naive symlink (or auto copy) may break these. Moreover, all example code rely on the `frb_rust` *by relative folder*, so if we want to execute tests after downloaded from pub.dev, we have to hackily modify the example code to use frb_rust *in crates.io*.
* Method 3: Another way if we care about self-contain. Maybe *move* everything in `frb_example` into `frb_dart/example`. Then, we solve the pub package problem. However, the "example depends on frb_rust in relative folder" problem still exists.

I personally prefers method 1 ;) IMHO I have not run tests for the packages downloaded from pub - when I need to run tests, usually it is because I want to PR to that lib, so I download the GitHub repository. However, if you think it is needed I can try to do method 2/3, or feel free to suggest any alternatives!

**Comment by dcharkes** [comment]
> * Method 1 (simplest): If we do not care about self-contained tests in pub.dev. In `frb_dart/test/pure_dart/main_test.dart`, simply call the main() of `frb_example/pure_dart/main.dart`, without any Valgrind, so it can be run easily, with test coverage, etc.

Hm, does that work? That would mean you need all the dependencies of the example project also in `frb_dart`, otherwise your imports don't resolve.

This sounds like a similar issue as in https://github.com/dart-lang/jnigen/issues/183#issuecomment-1429982950:

> For "Runtime" bindings, however, it probably leads to some amount of code duplication, because imports will be different.

We have a standalone test/example project, but also like to exercise those bindings directly in a test so that coverage works.

If we take a helicopter view of the situation, we'd probably want some of the same source code in both the Rust and Dart package to use for testing. And we'd like to avoid code duplication. So maybe it's unreasonable to ask the test infrastructure fits a simple Dart package (and a simple Rust package).

Because of this, it might make more sense to have a `frb_dart/test/README.md` that explains why the tests are not organized as a regular Dart package (instead of trying to shoehorn everything into the expected Dart package shape).

Please try to follow the Dart package conventions as much as possible. E.g. `frb_example/pure_dart/main.dart` should probably be `frb_example/pure_dart/bin/pure_dart.dart` (the simplest example) and `frb_example/pure_dart/test/pure_dart_test.dart` (everything). For more info see: https://dart.dev/tools/pub/package-layout.

**Comment by dcharkes** [comment]
SGTM! Thanks for taking the time to explain the constraints to me.

> [ ] frb_example/pure_dart/main.dart should probably be frb_example/pure_dart/bin/pure_dart.dart (the simplest example) and frb_example/pure_dart/test/pure_dart_test.dart (everything)

also for: frb_example/pure_dart_multi

**Comment by fzyzcjy** [comment]
> SGTM! Thanks for taking the time to explain the constraints to me.

Thanks for giving the suggestions!

> also for: frb_example/pure_dart_multi

TODO list added

**Comment by fzyzcjy** [comment]
Btw, is there a deadline for this (e.g. for Flutter Favorite)? If not, I may postpone a few days before implementing it, since I am too busy these days for anything that cannot be solved within 5 minutes...

Also cc @Desdaemon - do you have interest in this PR?

**Comment by Desdaemon** [comment]
Yeah, I could spend some time on this on the weekend.

**Comment by dcharkes** [comment]
> Btw, is there a deadline for this (e.g. for Flutter Favorite)? If not, I may postpone a few days before implementing it, since I am too busy these days for anything that cannot be solved within 5 minutes...

I do not have much insight into the process, so I cannot say. Given that I work on FFIgen and JNIgen, I'm probably the most knowledgable reviewing FRB though. 🙂

**Comment by fzyzcjy** [comment]
bump

**Comment by fzyzcjy** [comment]
I am really busy recently (not only programming but also mathematics) and thus have not been able to find a time slot... Anyway this is in my todo list!

**Comment by fzyzcjy** [comment]
(hmm the bot does not seem to recognize my reply...)
