### ISSUE TITLE
In dart language implement a  trait in rust language

### ISSUE THREAD

**Issue by shuchaodong** [fzyzcjy/flutter_rust_bridge#1352]
Just like some define below:
In rust:
pub trait Test {
    async fn get_something(&self) -> Result<()>;
} 
How implement this trait in dart?

**Comment by fzyzcjy** [comment]
IMHO this is not possible directly now.

Quick brainstorm: A workaround may be

```rust
struct YourTraitImplByDartCallback {
  callback_get_something: DartCallbackObject,
}

impl YourTrait for YourTraitImplByDartClosure {
  fn get_something(&self) { self.callback_get_something() }
}
```

In other words, create a implementation, which *delegates* the real implementation into a dart callback. This `struct YourTraitImplByDartClosure` may be able to be generated automatically (since this looks like a stable pattern).

However, IIRC callbacks are not implemented yet as well, so to deal with it, you can, for example:

1. Implement it. This issue may be related (though that issue also discusses many other things): https://github.com/fzyzcjy/flutter_rust_bridge/issues/1132 ; IIRC there is an older issue related to callbacks but I have not found it
2. Simulate it by other means, such as an object pool with id
