### ISSUE TITLE
[Bug] Minor issues/improvements for frb attribute

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#1488]
### Describe the bug

Might open a PR soon after I'm done grokking the new v2 changes

- `#[frb(default)]` on parameters are not stripped, failing compilation
  - Requires detecting whether being expanded with cargo-expand or rustc (??)
  - Solution: rustc cfg flag at macro expansion only
- Token span information is not preserved, causing compiler errors to point at the attribute
- (feature) `#[frb(sync)]` on impl block to mark all functions as sync with opt-out

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
N/A
```

**Comment by fzyzcjy** [comment]
Totally agree and looking forward to the PR!

Btw, I ensured all v1 tests are passing, maybe I missed a few ones when I get dizzy copying and pasting?

**Comment by Desdaemon** [comment]
I think this is mostly with the new frb_macros implementation someone put in a few months back that I didn't personally review? Anyways the fix should be trivial

**Comment by Desdaemon** [comment]
This is the error coming from a function using `#[frb(default)]`:

```
error: documentation comments cannot be applied to function parameters
    --> polars-wrapper/src/wrapper.rs:1333:5
     |
1333 |     #[frb]
     |     ^^^^^^ doc comments are not allowed here
     |
     = note: this error originates in the attribute macro `frb` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by fzyzcjy** [comment]
> I think this is mostly with the new frb_macros implementation someone put in a few months back that I didn't personally review? Anyways the fix should be trivial

Then I guess we need to ensure edge cases are in our test set (in the future), since if so, that will cause CI failure automatically.

Btw, don't forget to read (new) contributor guides https://cjycode.com/flutter_rust_bridge/guides/contributing, especially the tips part, which explains `./frb_internal` script, etc

**Comment by fzyzcjy** [comment]
P.S. Since it is you who introduced `justfile` to this repo, maybe I explain a bit why I change to use dart to script: Because I realize FRB is growing so large that we need more features than justfile can provide. For example, we need to "iterate through a predefined list of package names and do something", while justfile does not support loop yet. Indeed I am still using justfile in many other open source projects, and also use it sparsely inside FRB, when there is no need for such complex grammars.

**Comment by Desdaemon** [comment]
> Btw, I am curious what do you think about working on this repo in v2, e.g. (new) contributor guides https://cjycode.com/flutter_rust_bridge/guides/contributing, especially the tips part, explains things ./frb_internal script, etc. Hope my refactor makes it a bit more fluent to work on the repo!

I think it looks great! Also the new frb_internal is a welcome change, kind of similar to how I used Dart to replace scripts in polars_dart and popular Rust libraries using cargo-xtask.

**Comment by fzyzcjy** [comment]
The PR is already merged
