### ISSUE TITLE
About the "pure_dart" case (add more doc about this)

### ISSUE THREAD

**Issue by ggslayer** [fzyzcjy/flutter_rust_bridge#1499]
Hi, I'm trying the bridge, In my case, I want my project struct like this:

flutter app   call a pure dart lib(created by -t package) called base.   In the "base" lib, integrate the rust by "flutter_rust_bridge_codegen integrate".   In the "base" lib, I will write a dart interface layer which will call auto-generated rust's generted dart method.

I find the doc see that:
```
If you want to use Rust with Dart (without Flutter), [here](https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/pure_dart) is a working example, and [here](https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/dart_minimal) is a minimal sample. Indeed, the former contains many tests of this library, and is constantly executed in [the CI](https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/.github/workflows/ci.yaml). Alternatively, [this tutorial](https://cjycode.com/flutter_rust_bridge/manual/miscellaneous/archived/tutorial-pure-dart) may be helpful.
```

I looked into the pure_dart example, but it include many files(like flutter_rust_bridge.yaml/...)  which I don't know how to generate them, I want to know, Is there auto tool like "flutter_rust_bridge_codegen integrate dart" exists?  Can you give me some advise about my case?  Thank you!

**Comment by fzyzcjy** [comment]
> flutter app call a pure dart lib(created by -t package) called base

I am not sure, this seems still a Flutter package, instead of a pure-Dart package?

* flutter create with whatever flag -> flutter package
* dart create -> pure dart package

If it is pure dart package, you need `build.dart` etc to hook the compilation neatly.

If it is Flutter package: I guess a quick way is:

* `flutter_rust_bridge_codegen create` (or whatever)
* Look at `./rust_builder` and `./rust`. The rust_builder is to be named `base` in your case, and `./rust` contains your rust code. Thus, you may need to move and rename these two folders.
* After move/rename, tweak a few configuration parameters to point to the correct location. (This article https://matejknopp.com/post/flutter_plugin_in_rust_with_no_prebuilt_binaries/ for cargokit may help; Also change flutter_rust_bridge.yaml a little bit)

**Comment by fzyzcjy** [comment]
I have updated the doc. Feel free to reopen the issue if needed!

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/5236035/d83e48b5-4255-41ec-9379-b63b6bdc848b)
