### ISSUE TITLE
Regarding crates import

### ISSUE THREAD

**Issue by ethicnology** [fzyzcjy/flutter_rust_bridge#1587]
Hello, thank you for the work on this topic, it seems very promising.

I have a question that I couldn't figure out myself while reading the documentation:

Is it possible to import a crate and use it in the flutter ?

If yes, is it mandatory to create a rust file to export/wrap these functions ?

Is there any tutorial on adding crates and using them in flutter thanks to the glue generated by this project ?

**Comment by OfficialBoyfriend** [comment]
You can import Rust Crate and use it in flutter, but you have to create a Rust file to export/wrap it.

The V2 version has just been released recently, and the documentation seems to be still being improved. For basic usage, maybe reading the template generated by "flutter_rust_bridge_codegen" is also a good choice.

**Comment by ethicnology** [comment]
Thank you for this fast answer

**Comment by fzyzcjy** [comment]
@OfficialBoyfriend Thanks for the quick reply!

In addition, I am also thinking about automatically exporting a whole crate to Flutter, without any needs to manually write a wrapper. However, that may have some difficulties, because, for example, it is hard (impossible?) to handle complex lifetimes, etc.

However, feel free to point out the crate you want to use, and we can have a look whether it is easy or hard :)
