### ISSUE TITLE
Naive question

### ISSUE THREAD

**Issue by ethicnology** [fzyzcjy/flutter_rust_bridge#1688]
I'm following this awesome project and I have a naive question.

Should I start to develop my package in Rust rather than Dart for my flutter apps ?

I could also imagine publishing a flutter package from rust code using `flutter_rust_bridge` to make it more convenient to import for flutter users 

What are the limitations to such approach (performances, platforms…) ?

**Comment by fzyzcjy** [comment]
> Should I start to develop my package in Rust rather than Dart for my flutter apps ?

It would be great to know roughly what is the package and I am happy to give more suggestions. Without more information, here is the section in readme for some general scenarios:

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/5236035/5bfd49ae-37cc-4d84-8bf3-a9a4489f1312)

**Comment by ethicnology** [comment]
- client to server data collection (analytics)
- API / Database wrappers
…

I'm expecting faster networks operations and payload serialization/deserialization, Am I wrong ?

**Comment by fzyzcjy** [comment]
> I'm expecting faster networks operations and payload serialization/deserialization, Am I wrong ?

Sure, Rust is usually faster than Dart. However, to be honest (I should not suggest Rust merely because I am creator of this package!), these are usually not computation heavy, so using Dart may be fast enough. On the other hand, for example, if you are going to use a database that only exists in Rust and has no Dart wrapper yet, then it is very reasonable to use this lib to create a simple wrapper.

**Comment by fzyzcjy** [comment]
You are welcome!
