### ISSUE TITLE
Crate name change

### ISSUE THREAD

**Issue by ghost** [fzyzcjy/flutter_rust_bridge#1750]
Do we have a possibility to provide a CLI to support modifying the name of the lib crate and synchronously modify the names of the linked libraries in the CMake files? Because simply changing the crate name from Cargo will not compile. Thank you!

**Comment by popzones** [comment]
# The Flutter tooling requires that developers have a version of Visual Studio
# installed that includes CMake 3.14 or later. You should not increase this
# version, as doing so will cause the plugin to fail to compile for some
# customers of the plugin.
cmake_minimum_required(VERSION 3.14)

# Project-level configuration.
set(PROJECT_NAME "rust_builder")
project(${PROJECT_NAME} LANGUAGES CXX)

include("../cargokit/cmake/cargokit.cmake")
apply_cargokit(${PROJECT_NAME} ../../../../../../rust **main2** "")

# List of absolute paths to libraries that should be bundled with the plugin.
# This list could contain prebuilt libraries, or libraries created by an
# external build triggered from this build file.
set(rust_builder_bundled_libraries
  "${${PROJECT_NAME}_cargokit_lib}"
  PARENT_SCOPE
)

**Comment by fzyzcjy** [comment]
Hi, currently this is not implemented, but feel free to PR for it! (I may not personally have time to do this, since this may not be super frequently used)

A workaround maybe, global search your crate name in the folder and rename everything.

Another workaround maybe, `flutterr_rust_bridge_codegen create` a brand new project with the new name, and then copy-paste your old code into the new folders.

**Comment by popzones** [comment]
Hi! Thank you for your reply. 

Yes. Both of your solutions are working. I have tried these two ways. We only need to modify the files under the rust_builder directory.

When I was familiar this project enough, I will try to create PR for it. Thank you.

**Comment by fzyzcjy** [comment]
You are welcome!
