### ISSUE TITLE
Using StreamSink and RustOpaque in external crate

### ISSUE THREAD

**Issue by EddieMataEwy** [fzyzcjy/flutter_rust_bridge#1785]
### Describe the bug

Now that in version 2 StreamSink and RustOpaque are in frb_generated.rs
How do we use them in external crates that are not in src/ or src/api ?
Before I could just import flutter_rust_bridge, but now?

### Steps to reproduce

Have a local crate in /rust/ directory.
You can import the crate from /src/api by specifying the path in cargo.toml
Try to pass StreamSink<u8>, for example, to external crate function...

### Logs

```shell
No logs
```

**Comment by fzyzcjy** [comment]
Firstly, I wonder whether it is best practice, e.g. should the external crate understand frb-specific things, or should be completely unaware of it in order to make the architecture more clear.

Secondly, in v2, usually you do not need to manually use `RustOpaque`, just write down arbitrary types, and frb will wrap the opaque for you automatically.

Thirdly, if you really want to use StreamSink here and there, there are some ways to solve this general issue of "suppose crate A depends on crate B, how to use crate A when inside crate B". For example, one way is to make a trait in crate B and make an impl in crate A.

**Comment by EddieMataEwy** [comment]
Yeah, I am thinking that I am going to try to use a thread scope where I call the function with a regular channel sender, and (still in scope) pass messages from the channel receiver to the StreamSink. A little weird because of scoping.Rust Opaque I believe I don’t have any issues for now, thanks.El 25 feb 2024, a las 23:26, fzyzcjy ***@***.***> escribió:﻿
Firstly, I wonder whether it is best practice, e.g. should the external crate understand frb-specific things, or should be completely unaware of it in order to make the architecture more clear.
Secondly, in v2, usually you do not need to manually use RustOpaque, just write down arbitrary types, and frb will wrap the opaque for you automatically.
Thirdly, if you really want to use StreamSink here and there, there are some ways to solve this general issue of "suppose crate A depends on crate B, how to use crate A when inside crate B". For example, one way is to make a trait in crate B and make an impl in crate A.

**Comment by fzyzcjy** [comment]
You are welcome!

P.S. Alternatively to the channel, it is also possible to make a simple wrapper type, or make a simple closure, etc.

**Comment by EddieMataEwy** [comment]
Yes. the closure is actually a lot better. Thank you!

**Comment by fzyzcjy** [comment]
You are welcome!
