### ISSUE TITLE
Support for Flutter Web Apps Built with "--wasm" Flag? 

### ISSUE THREAD

**Issue by tsavo-at-pieces** [fzyzcjy/flutter_rust_bridge#2179]
This might be a naive question but is it possible to build a flutter web app that leverages the new "--wasm" compilation mode and is still able to leverage an internal package that utilizes a wasm module generated through the ```flutter_rust_bridge_codegen build-web``` command?

**Comment by fzyzcjy** [comment]
I have not tried it personally, since it seems the flutter wasm requires browser to support WasmGC which is quite new and not many browser users have those browsers installed. However, since frb has migrated to the new js interop packages, theoretically it should work. Feel free to have a try and ping me if it does not work!

**Comment by powntheep** [comment]
It is producing this error with the version 2.1.0 and the base template code
![image](https://github.com/user-attachments/assets/b40fb13c-746f-492c-946c-8cc3f25f2a17)

**Comment by fzyzcjy** [comment]
Seems like https://github.com/fzyzcjy/flutter_rust_bridge/blob/9e5c6e54723700e8436bc76016173e0391befa8e/frb_dart/lib/src/dart_opaque/_web.dart#L1 is not migrated (indeed it seems to be the only one remaining? https://github.com/search?q=repo%3Afzyzcjy%2Fflutter_rust_bridge%20js_util&type=code)

Feel free to PR to migrate it to `dart:js_interop` which is usually trivial, or alternatively I will work on it later (but may not be very soon, since flutter wasm is quite experimental and only works in a small portion of browsers)

**Comment by fzyzcjy** [comment]
To be handled in https://github.com/fzyzcjy/flutter_rust_bridge/issues/2237 (hopefully within a week)
