### ISSUE TITLE
Advice:  transfer the logic of PartialEq from Rust to Dart

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#2238]
Currently(Frb v2.2.0), for a Rust type with macro like this 
```rust
#[derive(PartialEq, Eq, Debug, Serialize, Deserialize, Hash)]
pub enum ProxyNodeEnum {
    Trojan(TrojanNode),
    Vmess(VmessNode),
    Vless(VlessNode),
}

impl ProxyNodeEnum {
...
}
```
or manually written like this:
```rust
#[derive(Debug, Serialize, Deserialize, Hash)]
pub enum ProxyNodeEnum {
    Trojan(TrojanNode),
    Vmess(VmessNode),
    Vless(VlessNode),
}

impl PartialEq for ProxyNodeEnum {
    fn eq(&self, other: &Self) -> bool {
        self.get_name() == other.get_name()
    }
}

impl Eq for ProxyNodeEnum {}
```
The logic to compare the equivalence of  instance of the type can't be transferred to Dart.  As we know that Dart would generally compare the memory addresses of instances  but not content of the compared instance.

I hope this logic stated in Rust could be transferred to Dart, even not in default, at least it could be transferred by some flag setting or frb attribute macro tag.

**Comment by dbsxdbsx** [comment]
> Currently I guess you may workaround by: #[frb(name="operator==")] (and also remember the hashCode function).

After testing, seems that this `#[frb(name="operator==")]` takes no effect. 

> Yes, that looks quite reasonable and feel free to PR for this new feature!

I would give it a try after I finish my current job if this feature is still not implemented then.

**Comment by fzyzcjy** [comment]
> After testing, seems that this #[frb(name="operator==")] takes no effect.

Hmm, then maybe need to check what makes it ignored.

> I would give it a try after I finish my current job if this feature is still not implemented then.

Looking forward to it! I guess it will not be too hard, especially the v2 codebase is clearer than v1.

**Comment by SilverMira** [comment]
Currently, I'm using Riverpod which accepts a RustOpaque parameter which is obtained from public accessor of a non_opaque struct. However, since RustOpaque does not seem to have an underlying override of `operator==` and `hashCode`, Riverpod is not able to realize that the same underlying RustOpaque is being used across different calls.

```rs
#[frb(non_opaque)]
pub struct MyStruct {
   pub a: i32,
   pub b: third_party::SomeType
}

/// types.rs

pub use third_party::SomeType;
#[frb(opaque)]
#[frb(mirror(SomeType))
struct _SomeType();
```

For those that are facing this issue, the below seems to work fine:

```rs
/// types.rs
pub use third_party::SomeType;
#[frb(opaque)]
#[frb(mirror(SomeType))
#[frb(dart_code="
  @override
  bool operator ==(Object other) {
      return other is SomeType && equals(other as SomeType);
  }
")]
struct _SomeType();


#[ext]
pub(crate) impl SomeType {
  #[frb(sync)]
  #[frb(positional)]
  fn frb_override_equals(&self, other: &SomeType) -> bool {
    self == other
  }
}

```

Directly using  `#[frb(name="operator==")]` on `frb_override_equals` won't work because `Object.operator==` expects a `bool operator==(Object other)` signature, and so will result in `invalid_override` compilation error.

**Comment by fzyzcjy** [comment]
Brainstorm: Another way may be, put the custom dart_code in *both* SomeType and SomeTypeImpl.

**Comment by fzyzcjy** [comment]
Hmm, will changing `abstract class` to `abstract mixin class` be a breaking change? We need to ensure compatibility (unless creating 3.x)

And I am not sure that, since we expose SomeType to end users, they may feel confused "this is reasonable to be an abstract class, but why do you make it a mixin?". So I would like to hide the `mixin` if possible.

Copy-paste I guess is not a problem, since everything is auto-generated, which is unlike normal copy-pasting (which is a problem)

**Comment by SilverMira** [comment]
I'm fairly certain `abstract class` to `abstract mixin class` is not a breaking change, see [Dart 3.0 class modifiers](https://github.com/dart-lang/language/blob/main/accepted/3.0/class-modifiers/feature-specification.md#syntax). It just enables the class to be used as a mixin along side what the `abstract class` already allows (to be extended from, or to be implemented).

As for changing `implements` to `class SomeTypeImpl extends RustOpaque with SomeType`, it shouldn't be breaking too unless `SomeType` have concrete members that FRB itself is generating already (I can't confirm on this), since using `with` would mean `SomeTypeImpl` will get inherit all the concrete behaviors (methods/properties) from `SomeType`.

**Comment by SilverMira** [comment]
> This does add some code, but at least semantically easy to maintain. Just for reference, I am not familiar with RiverPod , don't know if there is similar way to work around your case.

Or course there are ways to workaround the issue, I can use riverpod to cache the opaque type (which will remain usable until eventually a method that moves the opaque type is called if any). But it does feel that the ergonomics can be improved here without all the manual plumbing work
