### ISSUE TITLE
Attribute documentation

### ISSUE THREAD

**Issue by mezeipetister** [fzyzcjy/flutter_rust_bridge#2264]
Hi could you help me where to find docs about ui_state and ui_mutation attributes? Thank you in advance.

**Comment by fzyzcjy** [comment]
Hi, I have not written docs about this since this is not stablized yet (but since this is a fairly thin wrapper there is no hidden secrets). Currently, you can have a look at two examples in https://cjycode.com/posts/rust-ui-flutter/.

And here is what I may be write in doc:

* Write `#[frb(ui_state)] pub struct RustState { ... }`
* For functions that will mutate the state, write like `#[frb(ui_mutation)] impl RustState { fn your_function(...) {} }`. Then, when the function is called, the Dart UI will be notified to auto rebuild (i.e. `setState` in Dart if you knew it).
