### ISSUE TITLE
Allow ui_state attribute to be used with arbitrary associated struct name

### ISSUE THREAD

**Issue by Vollbrecht** [fzyzcjy/flutter_rust_bridge#2337]
**Is your feature request related to a problem? Please describe.**
Its not documented and non intuitive that the ui_state attribute can only be used  with something that is exactly called `RustState`

**Describe the solution you'd like**
Allow for arbitrary struct naming of a struct annotated with ui_state

**Describe alternatives you've considered**
Warn the user if he uses the ui_state attribute on a struct that is not exactly `RustState` and document this implicit behavior.

**Comment by fzyzcjy** [comment]
Totally agree, we should support that! (Originally it was more like a quick demo so was quite minimal) Feel free to PR, alternatively I will work on it later (may not guarantee to be within days since this is related to experimental feature).

Btw possibly related: https://github.com/fzyzcjy/flutter_rust_bridge/issues/2307
