### ISSUE TITLE
[Bug] StreamSink starving memory

### ISSUE THREAD

**Issue by thunderstorm010** [fzyzcjy/flutter_rust_bridge#2373]
Hi. I'm trying to stream video frames (in this example Vec<u8>) from Rust to Flutter. But frb seems to eat more and more RAM growing exponentially.

Here is my code:
```rust
pub fn stream_video(stream_sink: StreamSink<Vec<u8>>, pipeline: String) -> anyhow::Result<()> {
    gstreamer::init().unwrap();
    let element = gstreamer::parse::launch(&pipeline)?;
    let bin = element
        .downcast::<Bin>()
        .map_err(|_| anyhow::anyhow!("Failed to downcast initial element to bin"))?;
    let sink_element = bin.by_name("video-sink").ok_or(anyhow::anyhow!("Failed to find appsink named video-sink. The pipeline should always end with an appsink named video-sink"))?;
    let sink = sink_element.downcast::<gstreamer_app::AppSink>().map_err(|_| anyhow::anyhow!("Failed to map sink element to appsink. The pipeline should always end with an appsink"))?;
    bin.set_state(gstreamer::State::Playing).unwrap();
    std::thread::spawn(move || {
        loop {
            let sample = sink.pull_sample().unwrap();
            let buf = sample.buffer().unwrap().map_readable().unwrap().to_vec();
            stream_sink.add(buf).unwrap();
        }   
    });
    Ok(())
}
```
Notes:
1) Removing the line with `stream_sink.add` results in constant memory use (aka no problem.) (I think this means the problem is not with Gstreamer)
2) Even when I remove the dart side code handling the stream (inside the Stream.listen function), memory use continues to grow.
3) If further information is needed, just write a comment and I will answer asap.

Thanks for everything

**Comment by fzyzcjy** [comment]
Hi, could you please make a minimal reproducible sample? For example, maybe 

```
pub fn f(sink: StreamSink<Vec<u8>>) {
  loop {
    sink.add(vec![0; 1000000]);
    sleep(100ms);
  }
}
```

And to debug, also try to do manually trigger a (full) GC on Dart side, and see whether memory is better.

And try dart's devtool's memory part, to see what is eating a lot of memory, and why they are alive instead of GCed.

**Comment by fzyzcjy** [comment]
Btw, if you want to show videos, then I guess it is great to avoid such rust-to-dart transfer, because after you transfer the bytes to Dart, indeed dart has to again transfer to its engine and display, which is quite long and slow.

One possible way may be, use https://github.com/irondash/irondash/tree/main/texture. Then the rust gstreamer frames can directly be displayed to screen, and the rest of the app can be written in Flutter.

Possibly related: https://github.com/fzyzcjy/flutter_rust_bridge/issues/1776

**Comment by thunderstorm010** [comment]
Hi, firstly thanks for your answer.

I tried irondash, and after some fiddling around I've finally got it to work. I don't have problems anymore, and also kudos to the owner of irondash as well

**Comment by fzyzcjy** [comment]
Hi, happy to see it works! Btw if you see any bugs (such as the starving memory issue) with reproducible sample, feel free to ping me.

> also kudos to the owner of irondash as well

cc @knopp (owner or irondash) :)

**Comment by fzyzcjy** [comment]
Close since this seems to be solved, but feel free to reopen if you have any questions!
