### ISSUE TITLE
`implements` missing

### ISSUE THREAD

**Issue by Larpoux** [fzyzcjy/flutter_rust_bridge#2428]
Hi, Guys, Girls and Ladyboys. I have bad news for you : I am back!!! 👀 .

No, I am kidding. I have finished  to port my project implementation on Javascript, and I return to Rust to have a native implementation of my interface.

Actually I have something weird : 
```rust
pub trait AudioScheduledSourceNode: AudioNode {
...
```
generates : 
``` dart
abstract class AudioScheduledSourceNode {
```
Without specifying `implements AudioNode`. Do you have any idea of the reason ?

**Comment by fzyzcjy** [comment]
Happy to see you back! 

> Without specifying implements AudioNode

Firstly, does it work before (i.e. in some other code)? If no, then I guess this is a not-yet-implemented feature. If yes then it is a bug.

To implement it, we can either do it fully automatically (i.e. parse the parent trait name etc), or we can add something like `#[frb(dart_implements = "AudioNode")]` to allow users to add arbitrary `implements` or `extends` etc. I personally think the latter is needed because there can be other cases when we want a custom `implements/extends`.

**Comment by fzyzcjy** [comment]
@Larpoux @raphaelrobert Feel free to PR! Alternatively, I will work on it in the next batch.

**Comment by Larpoux** [comment]
I am busy working on a port of the rust library to dart.
Actually I am not completely sure that there is real problem with this issue.
I will let you know later how things are going. Don’t do anything until then.

**Comment by fzyzcjy** [comment]
Ok, no worries and feel free to ping me when needed!
