### ISSUE TITLE
Recursively incorporate structs and enums defined in external library

### ISSUE THREAD

**Issue by AlienKevin** [fzyzcjy/flutter_rust_bridge#249]
**Is your feature request related to a problem? Please describe.**
I'm looking to pass a complex struct defined in an external parser library to dart for display. However, [codegen](https://github.com/fzyzcjy/flutter_rust_bridge/blob/a37de72aee18ea28a7511026e51b953c912ab03c/frb_codegen/src/parser.rs#L307) only looks for structs and enums in the current file.

**Describe the solution you'd like**
Recursively lookup library files for missing struct and enum definitions.

**Describe alternatives you've considered**
Essentially copying the library definitions over to api.rs. However, this produces duplicated definitions and is not practical for complex definitions.

**Comment by fzyzcjy** [comment]
Sounds reasonable! You can make a PR I am willing to review it ;)

**Comment by AlienKevin** [comment]
Currently, since the complex struct also contains enums with fields, which are not supported by flutter-rust-bridge, I will try to convert it into HTML and display the HTML in flutter for now. If this does not work out, I will go tackle the harder problem of adding support to flutter-rust-bridge.

**Comment by fzyzcjy** [comment]
> complex struct also contains enums with fields

I have an idea: What about generating Flutter/Dart code using the "Flutter Favorite" package https://pub.dev/packages/freezed 

It supports union/sealed classes, which is equivalent to Rust enum with fields:

https://pub.dev/packages/freezed#unionssealed-classes

For example

```
enum Union {
  Data(value: i32),
  Loading,
  Error({message: String}),
}
```

becomes

```
@freezed
class Union with _$Union {
  const factory Union(int value) = Data;
  const factory Union.loading() = Loading;
  const factory Union.error([String? message]) = ErrorDetails;
}
```

Possibly related: #238 #239 and @Desdaemon (hi are you interested in that?)

**Comment by Desdaemon** [comment]
I am quite intrigued with this idea, but I am also worried about the ergonomics of sum types in Dart. Using `freezed` introduces another build step which I was not too fond of, unless if anyone can share their experiences using it in practice? Personally I think this will be easy to implement, but hard to utilize.

On the topic of gathering type definitions, I'm thinking about maybe converting `use` expressions into Dart imports, then it could go in one of these two ways:
- A Rust module visitor to find `use` statements and generate adapters for them;
- Or our program accepts a list of files/folders to convert and an output folder.

I'm not quite sure how the former will go, but the latter solution mirrors what tsc does: only process the files that are requested.

**Comment by fzyzcjy** [comment]
> Using freezed introduces another build step which I was not too fond of, unless if anyone can share their experiences using it in practice?

Very standard practice indeed ;) For example, almost everyone uses `json_serializable` Flutter library, then everyone has already used the built-in code generator of Flutter. Thus, adding `freezed` is nothing more for a Flutter user.

**Comment by fzyzcjy** [comment]
#256 merged

**Comment by SecondFlight** [comment]
I think I've identified a possible solution, but I'd like to double-check that it makes sense.

My thought is to refactor `extract_items_from_file` from `parser.rs` into two steps: one that identifies the types that are relevant to the API functions, and another that collects these types and their dependents.

The naive option is simply to make the existing implementation recursive, but I think that would result in collecting types from every file in the entire dependency tree and I don't feel great about that.

### Goal
Recursively extract all relevant types (custom structs or enums)

### Strategy
1. Collect all functions in the API file.
2. Loop over functions and collect all argument types and return types. For each type that is unknown, add it to a list of relevant types.
3. Collect all relevant dependent types:
  a. Collect types that are defined in this file, but only if they also exist in our list of relevant types.
  b. For each type collected in step a, identify the types it depends on. Add them to our list of relevant types.
  c. Loop through imports and collect imports that match our list of relevant types.
  d. For each import collected in step c, visit the file linked to by that import and repeat steps a. through d. on that file.
4. Add all types collected in step 3 to our list of relevant types.

**Comment by fzyzcjy** [comment]
@SecondFlight Sounds great!

Just my two cents: We may also refer to https://github.com/eqrion/cbindgen to see how they use `syn` to extract those information. (Or even create an issue there asking)

**Comment by SecondFlight** [comment]
It's been a little while, so a quick progress report:

I've spent some spare time over a few days on this (and I've missed a few more due to being sick). As often happens, the implementation is turning out to have a lot of hidden complexity.

Parsing `use` statements is not trivial, and is quickly becoming the biggest issue with the steps above. `syn` will produce an AST from a source file, but it doesn't seem to offer much help in making sense of that source. This includes `use` statements; I can't just ask `syn` what an import points to. So in order to fulfill the steps above, I think I'll need to write code that can generically determine where a symbol comes from.

I've spent some time digging into the `cbindgen` source, particularly `parse.rs` and `cargo/*.rs`, but I still don't feel I've internalized what's going on. However, I have read enough to be very unsure that I'm going down the right path. I haven't found anything indicating that `cbindgen` resolves `use` statements at all, but I also haven't figured out if/how it sidesteps that problem.

I have a lot of holes in my understanding, but I'm wondering if `cbindgen` is using `rustc -- -Zunpretty=expanded` to solve this problem. There is code in their source for it (see [here](https://github.com/eqrion/cbindgen/blob/master/src/bindgen/cargo/cargo_expand.rs), and it would greatly simplify the problem. The issue with trying this technique in `flutter_rust_bridge` is that `flutter_rust_bridge` runs before the crate can actually build, which I think rules out this as an option, except when dealing with dependencies.

I think my best option based on my current understanding is:
1. Parse the API file and pull files and dependencies that it references, possibly limiting the ways in which a dependency can be referenced (e.g. no wildcard imports). Process any symbols in local files.
2. Parse the crate containing the API file and figure out its dependencies. Pull out and process any symbols in the dependencies that are referenced by the API file.

These steps can be implemented separately. I'm trying to unblock another project of mine which only needs step 1, so my focus would be there right now.

My biggest worry is that I'm missing something and I'll spend the next few weeks writing up a complex solution, only to find that there was a simple one staring me in the face. I still feel I'm in that limbo stage in understanding the problem, where you know enough to be dangerous but not enough to be effective.

Please let me know if you have any thoughts or ideas here!

**Comment by fzyzcjy** [comment]
> and I've missed a few more due to being sick

Sorry to hear that :( Hope you get well soon!

> Parsing use statements is not trivial, and is quickly becoming the biggest issue with the steps above. syn will produce an AST from a source file, but it doesn't seem to offer much help in making sense of that source. This includes use statements; I can't just ask syn what an import points to. So in order to fulfill the steps above, I think I'll need to write code that can generically determine where a symbol comes from.

Btw, we may extract this part of logic into a separate file or even a separate crate, such that later people implementing "somethingelse-rust-bridge" can benefit from it

> that flutter_rust_bridge runs before the crate can actually build, which I think rules out this as an option, except when dealing with dependencies.

as for this concrete problem, what about generating some dummy code. (not sure whether we have enough information for this provided the complexity mentioned above though...) Or, can we exploit it without a compilable code?

> possibly limiting the ways in which a dependency can be referenced (e.g. no wildcard imports)

Agree. That should not be a big problem for users.

> These steps can be implemented separately. I'm trying to unblock another project of mine which only needs step 1, so my focus would be there right now.

Step 1 is already very expressive, so your work is important.

> My biggest worry is that I'm missing something and I'll spend the next few weeks writing up a complex solution, only to find that there was a simple one staring me in the face. I still feel I'm in that limbo stage in understanding the problem, where you know enough to be dangerous but not enough to be effective.

In Dart/Flutter, the provided builder package is quite great and can tell me which symbol comes from where etc. What if rust have such a great thing and we can solve it easily!

What about asking more people, e.g.

* Create issues in cbindgen and similar libraries asking them how they implemented it. Sometimes it may be easier if you extract that part into a separate crate (then both them and us benefit from it - they have cleaner code, we have a mature tool)
* Ask at StackOverflow
* Ask at Reddit
* ...

**Comment by fzyzcjy** [comment]
> This didn't cross my mind. Nothing else imports the generated file, so putting a dummy file there should work, right?

Sounds yes (may have an experiment about it, but theoretically seems yes)

> causes the rebuild time (not a clean build) to jump to over 5 minutes for me which is completely unworkable.

Interesting... 5min is really not acceptable.

> where I feel that asking them would be equivalent to "Hey, I don't really feel like reading your source code, could you explain it to me?"

Maybe, instead, create an issue saying "hey I am willing to refactor cbindgen and extract the part of parser such that other programmers can happily use it, could you plz give some hints". Just a tiny suggestion

> I think my next course will be using rustc with a dummy generated file as mentioned above and seeing how far I get with that. I'll reevaluate if I get stuck there. Thanks for the suggestion!

You are welcome! Looking forward to your progress

**Comment by fzyzcjy** [comment]
Cross-linking: 

https://github.com/fzyzcjy/flutter_rust_bridge/issues/303 @saward also wants this feature

**Comment by SecondFlight** [comment]
Another while, another update.

I feel a bit less insane after finding this in [the cbindgen docs](https://github.com/eqrion/cbindgen/blob/master/docs.md#writing-your-c-api):
> 🚨 NOTE: A major limitation of cbindgen is that it does not understand Rust's module system or namespacing. This means that if cbindgen sees that it needs the definition for MyType and there exists two things in your project with the type name MyType, it won't know what to do. Currently, cbindgen's behaviour is unspecified if this happens. However this may be ok if they have [different cfgs](https://github.com/eqrion/cbindgen/blob/master/docs.md#defines-and-cfgs).

So I spent last couple weeks writing a module parser. The source can be found here: https://github.com/SecondFlight/flutter_rust_bridge/blob/external-typedefs/frb_codegen/src/source_graph/source_graph.rs

The code I wrote can map out all modules, imports, enums and structs in a crate.

For example, this file...
```rust
pub struct MyStruct;

pub enum MyEnum {
    One,
    Two,
}

mod abc {
    pub struct InFileNestedTest;

    mod one {}
    mod two {}
}

pub use abc::{one, two};
```

... will be parsed into this `Module`:
```
Module {
    visibility: Inherited,
    module_path: [
        "crate",
        "data",
    ],
    file_path: "(...)\\src\\data.rs",
    source: "omitted",
    scope: Some(
        ModuleScope {
            modules: [
                Module {
                    visibility: Inherited,
                    module_path: [
                        "crate",
                        "data",
                        "abc",
                    ],
                    file_path: "(...)\\src\\data.rs",
                    source: "omitted",
                    scope: Some(
                        ModuleScope {
                            modules: [
                                Module {
                                    visibility: Inherited,
                                    module_path: [
                                        "crate",
                                        "data",
                                        "abc",
                                        "one",
                                    ],
                                    file_path: "(...)\\src\\data.rs",
                                    source: "omitted",
                                    scope: Some(
                                        ModuleScope {
                                            modules: [],
                                            enums: [],
                                            structs: [],
                                            imports: [],
                                        },
                                    ),
                                },
                                Module {
                                    visibility: Inherited,
                                    module_path: [
                                        "crate",
                                        "data",
                                        "abc",
                                        "two",
                                    ],
                                    file_path: "(...)\\src\\data.rs",
                                    source: "omitted",
                                    scope: Some(
                                        ModuleScope {
                                            modules: [],
                                            enums: [],
                                            structs: [],
                                            imports: [],
                                        },
                                    ),
                                },
                            ],
                            enums: [],
                            structs: [
                                Struct {
                                    ident: Ident(
                                        InFileNestedTest,
                                    ),
                                    visibility: Public,
                                },
                            ],
                            imports: [],
                        },
                    ),
                },
            ],
            enums: [
                Enum {
                    ident: Ident(
                        MyEnum,
                    ),
                    visibility: Public,
                },
            ],
            structs: [
                Struct {
                    ident: Ident(
                        MyStruct,
                    ),
                    visibility: Public,
                },
            ],
            imports: [
                Import {
                    path: [
                        "abc",
                        "one",
                    ],
                    visibility: Public,
                },
                Import {
                    path: [
                        "abc",
                        "two",
                    ],
                    visibility: Public,
                },
            ],
        },
    ),
}
```

Here are some things this code can do:
- Map modules that are in the same file (`mod { }`)
- Map modules that are external, but within the crate (`mod abc;` -> `./abc.rs` or `./abc/mod.rs`)
- Map imports, including group imports and wildcards (`use a::b::*`, `use a::{b::c, d::e}`)
- Map enums and structs within each module's scope

And some things it can't do:
- Understand import renames (`use a::b as c`), though it wouldn't be too hard to support this
- Map a crate's dependencies. To do this, I'd need to write code to discover the on-disk location of resolved dependencies. This is definitely doable, but I'm considering this outside of my scope for now.
- Pass unit tests, since I haven't written any yet :)

I'm not comfortable releasing this as a library yet as it certainly isn't general-purpose and probably has some awful edge cases. I'm happy to be convinced otherwise though.

My next task is to update the codegen to use this tool. I'm hoping this won't be too hard, but I haven't dug into the current code so I'm not sure what will be needed. I'll definitely ask here if I get stuck.

**Comment by fzyzcjy** [comment]
Happy to hear you update and looking forward to your PR! (You can create a "Draft" PR now as well if you like)

> NOTE: A major limitation of cbindgen is that it does not understand Rust's module system or namespacing. This means that if cbindgen sees that it needs the definition for MyType and there exists two things in your project with the type name MyType, it won't know what to do.

Interesting. So I guess it just use a big pool mapping names to definitions?

> So I spent last couple weeks writing a module parser. The source can be found here:

Great work! It sounds already pretty powerful and can cover many usage cases!

> Pass unit tests, since I haven't written any yet :)

One approach is to write down some code in the frb_examples/pure_dart/rust/api.rs (and dart/main.dart and so on) and run code generator and expect it to work. This is more like integration test.

Another approach is to write some pure-rust tests and use `cargo test` to run it. This is more like unit tests.

> I'm not comfortable releasing this as a library yet as it certainly isn't general-purpose and probably has some awful edge cases. I'm happy to be convinced otherwise though.

The current approach (just put source code in subfolder) sounds also quite good. No worries

> My next task is to update the codegen to use this tool. I'm hoping this won't be too hard, but I haven't dug into the current code so I'm not sure what will be needed. I'll definitely ask here if I get stuck.

Sure. I am usually online.
