### ISSUE TITLE
The `.freezed.dart` is not automatically generated, making the users confused

### ISSUE THREAD

**Issue by Unoqwy** [fzyzcjy/flutter_rust_bridge#344]
The freezed declaration file doesn't get generated. The declaration file does include `part 'bridge_generated.freezed.dart';` in the header, but the file doesn't exist. There is no error in the codegen output so I assume this is a bug, probably a side effect of the heavy refactoring going on.
Also, there is no flag to customize the name of this file, it would be a nice addition for consistency (well, once the file actually generates).

**Comment by fzyzcjy** [comment]
Maybe we can solve the confusion by invoking `build_runner` automatically when `flutter_rust_bridge` command executes, just like what we have done for `ffigen` and `cbindgen` and so on.

Notice that, we need to ensure that we *only run `build_runner` for that single dart file* instead of running for the whole dart project (o/w can be very slow). This link https://github.com/dart-lang/build/issues/2928 may be related.

@Desdaemon What do you think about it?

**Comment by Desdaemon** [comment]
> Maybe we can solve the confusion by invoking build_runner automatically when flutter_rust_bridge command executes, just like what we have done for ffigen and cbindgen and so on.

I think this might be the right way to go, but we need a way to find the root of the Dart library in case it is not the current directory. As for the hardcoded name, I'll have a PR within a few days.

**Comment by fzyzcjy** [comment]
@Desdaemon 

> but we need a way to find the root of the Dart library in case it is not the current directory

What about the same heuristics we have used (?) to find the rust crate:

1. go to the parents of the generated `.dart` file until find a `pubspec.yaml`.
2. allow users to specify the package folder manually

**Comment by Unoqwy** [comment]
> Well you should execute dart build runner manually by yourself. frb currently does not auto run that. Doc: https://github.com/Desdaemon/flutter_rust_bridge/blob/doc_fix/book/src/generate/build_runner.md

Ah alright, thank you.

**Comment by fzyzcjy** [comment]
You are welcome!
