### ISSUE TITLE
Write documentation on integration with Flutter's new FFI plugin structure

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#531]
Reference: https://docs.flutter.dev/development/packages-and-plugins/developing-packages#plugin-ffi

Currently, `flutter create -t plugin_ffi` generates a C library directly consumable by Flutter on all non-Web platforms. It might be interesting to see how we can update our book to replace the included C library with Rust and streamline the setup process.

**Comment by Andrflor** [comment]
One issue with the plugin_ffi template is that it builds the lib when you run flutter run.
But since you will never change the lib on the consumer side building it is not a good option.

Any consumer of your lib then must have the proper rust toolchain to build the lib...
The consumer will rebuild the lib on every flutter clean.
This will also increase ci time and complexify ci config for nothing.

Starting with that idea in mind here is a proposal:

Starting from that template we could remove src and replace it with our native folder containing rust code.
Then we could create a  folder named "libs" in each platform folder containing the compiled libs.

We could modify ffigen.yaml to fit our needs or just remove it.

Then we can link the library.
For example for linux and windows by replacing content of CMakeLists.txt

Linux:
```cmake
set(CRATE_NAME "myLibName")

add_library(${CRATE_NAME} STATIC IMPORTED GLOBAL)
set_property(TARGET ${CRATE_NAME} PROPERTY IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/libs/lib${CRATE_NAME}.so")

set(extractor_bundled_libraries
  $<TARGET_FILE:${CRATE_NAME}>
  PARENT_SCOPE
)
```

Windows:
```cmake
set(CRATE_NAME "myLibName")

add_library(${CRATE_NAME} SHARED IMPORTED GLOBAL)
set_property(TARGET ${CRATE_NAME} PROPERTY IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/${CRATE_NAME}.dll")

set(extractor_bundled_libraries
  $<TARGET_FILE:${CRATE_NAME}>
  PARENT_SCOPE
)
```

For android we could diff build.gradle
```diff
-    // Invoke the shared CMake build with the Android Gradle Plugin.
-    externalNativeBuild {
-        cmake {
-            path "../native/CMakeLists.txt"
-
-            // The default CMake version for the Android Gradle Plugin is 3.10.2.
-            // https://developer.android.com/studio/projects/install-ndk#vanilla_cmake
-            //
-            // The Flutter tooling requires that developers have CMake 3.10 or later
-            // installed. You should not increase this version, as doing so will cause
-            // the plugin to fail to compile for some customers of the plugin.
-            // version "3.10.2"
-        }
-    }

+    // Bundle the jniLibs in the libs folder
+    sourceSets {
+        main {
+            jniLibs.srcDirs = ['libs']
+        }
+    }
```
I still need to investiagate Ios and mac, I will update when done.

The main issue is that there is no automation process for building the libs, but is that a real problem?
Or may we make a script to build and copy on the right locations? Even if it's just one command per platform?

What do you think about that idea?

**Comment by Desdaemon** [comment]
> Or may we make a script to build and copy on the right locations? Even if it's just one command per platform?

Nice idea, this works better for plugin authors who would like to have a different build file for development vs. pulling precompiled binaries.

**Comment by Desdaemon** [comment]
Related:
- Desdaemon/flutter_rust_bridge_template#22
- Desdaemon/flutter_rust_bridge_template#24
