### ISSUE TITLE
Shall we support implicit type conversion to `u64`/`usize` or force explicit type conversion?

### ISSUE THREAD

**Issue by gcxfd** [fzyzcjy/flutter_rust_bridge#69]
as title

**Comment by fzyzcjy** [comment]
Surely I can support that. The problem is: Is it the correct thing to do?

In Rust, there seems nothing as automatic type conversion. For example, when doing `a+b`, if their type does not match, we have to do things like `a + b as i32`, etc. Therefore, since Dart does not have a u64 type (thus also not usize - if it is on 64bit machine which often does), providing a `u64` from Rust to Dart can cause numerical overflow.

If you really need that "unsigned" part, i.e. you cannot use i64 but have to use u64, I think the deliberate lack of ability actually helps you instead of harms you. With the lack, you notice this problem; without the lack, the code will behave incorrectly silently, which disobey Rust's philosophy.

On the other hand, if you do not need the "unsigned" part, i.e. your value can always be fit into a i64, then using i64 does not cause problems.
