### ISSUE TITLE
Flutter package web settings

### ISSUE THREAD

**Issue by Andrflor** [fzyzcjy/flutter_rust_bridge#857]
Hi, a big thank for you work :)

I created a ffiPlugin (flutter package) relying on pre-compiled binaries working on Windows, Mac, Linux, Android and Ios.
Now that there is  web capability I try to add **Web** support to my flutter package with pre-compiled js/wasm.
But I can't figure out how to do so.

I have generated the proper new bindings with proper **Web** import and successfully built it using wasm-pack.

But I still encounter two issues:
- How can I link the /web/pkg folder of my library to my main app ?
 At the moment I have to manually copy paste from (my_package)/web/pkg into (my_app)/build/web/pkg.

- How can I manage to resolve CORS ? 
  I followed the doc but setting the requested headers prevent  **CanvatKit** to load thus preventing flutter to load properly.

Flutter 3.0.5
Dart 2.19.0
flutter_rust_bridge 1.49.2

Someone having any idea about that?
Or maybe someone as already done that kind of build?

**Comment by Desdaemon** [comment]
Hi, sorry for the delay in responding!

1. Sadly, this is a limitation of `flutter run`'s support for the web. I wrote `flutter_rust_bridge_serve` in order to circumvent similar issues, so you might be able to handle the library case using it as well.

2. This is another issue that I encountered myself when testing WASM. This can only be fixed upstream, but hopefully it is trivial enough (adding a `crossorigin='anonymous'` to the failing request)

**Comment by elliotsayes** [comment]
Hi! Just to clarify here: is there presently a way to use a dart/flutter **package**/plugin that uses flutter_rust_bridge on the web? If it is indeed possible, is there any guide on how to do this (either in the package side or manual steps in the depending flutter project)?
Would prefer to make my package code reusable on pub.dev if possible, so any help appreciated!
