### ISSUE TITLE
Support ZeroCopyBuffer<Vec<[u8, 32]>>

### ISSUE THREAD

**Issue by pauldemarco** [fzyzcjy/flutter_rust_bridge#955]
Would it be possible to support a ZeroCopyBuffer of a Vec of arrays?

**Comment by fzyzcjy** [comment]
IMHO no directly, which is a limitation of Dart programming language.

However it is indeed possible: Since `Vec<[u8;32]>` is nothing but a continuous chunk of memory, so it can be converted to `Vec<u8>` and thus sent directly, and in the Dart side use the Dart's array "view"s feature to recover it.

Feel free to PR!

**Comment by pauldemarco** [comment]
Oh wow, that's an interesting idea. I'll give it a shot!

**Comment by fzyzcjy** [comment]
Looking forward to it!
