### ISSUE TITLE
Rust Support for Android NDK r25 (yay!)

### ISSUE THREAD

**Issue by initiativist** [fzyzcjy/flutter_rust_bridge#995]
**Is your feature request related to a problem? Please describe.**
Looks like Rust 1.68 has support for more recent Android NDK versions.

https://blog.rust-lang.org/2023/01/09/android-ndk-update-r25.html

Specifically I noticed the documentation mentioned having to use older versions.

I'm not sure if this is the right place for this as this is my first github contribution, please direct me if there's a better way to introduce something like this.

**Comment by fzyzcjy** [comment]
That looks interesting!

If we are going to support r25, we should ensure that the old versions are *still supported* and well-tested, because we surely cannot enforce everyone to use Rust 1.68 :)

Btw you can use git blame to find who wrote the "use older versions" part and cc him here. I guess @Desdaemon ? (who did a lot of good job in tutorials)

**Comment by dbsxdbsx** [comment]
For this issue, recently with the latest NDK and latest Rust, one of my frb projects can't get compile for Android, with OpenSSL [issue](https://github.com/sfackler/rust-openssl/issues/1793).  This frb project has no issue if targeting windows app.  And my other frb project has no such issue when targeting Android. I think maybe it is due to I used some net crates in rust(`reqwest`...), before when this project can still get compiled on Android.

(I am not sure if my issue is related to this. Just mention it here.)

**Comment by Desdaemon** [comment]
Was this solved by #1096?

**Comment by initiativist** [comment]
Seems to be well documented in the linked PR!
